"""Updated price field type

Revision ID: 398999a13177
Revises: c8491f2a5359
Create Date: 2025-06-20 14:29:12.090137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398999a13177'
down_revision = 'c8491f2a5359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
