"""add_guest_checkout_fields

Revision ID: 4a3cb5d7bd1f
Revises: 869b1c64d92b
Create Date: 2025-11-05 08:58:32.910300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3cb5d7bd1f'
down_revision = '869b1c64d92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guest_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('guest_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_instructions', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('delivery_instructions')
        batch_op.drop_column('delivery_city')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('guest_phone')
        batch_op.drop_column('guest_email')
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###
