"""Add payment gateway fields to Order model

Revision ID: 869b1c64d92b
Revises: c38d4ce03f3c
Create Date: 2025-10-13 11:47:04.301631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869b1c64d92b'
down_revision = 'c38d4ce03f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_transaction_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('amount')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_transaction_id')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
