"""Make shoe_id nullable in orders

Revision ID: 9f512e983c6d
Revises: 398999a13177
Create Date: 2025-06-20 14:50:17.801363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f512e983c6d'
down_revision = '398999a13177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('shoe_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('shoe_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
