"""Add admin hierarchy fields

Revision ID: c38d4ce03f3c
Revises: 9f512e983c6d
Create Date: 2025-09-25 09:56:27.515861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38d4ce03f3c'
down_revision = '9f512e983c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_shoes_created_by', 'users', ['created_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('product_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('product_limit')
        batch_op.drop_column('admin_type')

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shoes_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
